pool:
  vmImage: "ubuntu-16.04"

steps:
- task: Gradle@2
  env:
    LAUNCHER_SENTRY_DSN: $(SENTRY_DSN)
    LAUNCHER_CI: 'true'
  inputs:
    workingDirectory: ''
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    tasks: 'setup build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/build/libs/MyFTBLauncher.app'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/MyFTBLauncher.app.zip'

- task: CopyFiles@2
  inputs:
    contents: '**/build/libs/*.jar'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'launcher'